spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: false
  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: health,logfile
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    path: logs/
    name: application.log
