spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: false