spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: false