spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BookMigration
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2